change
aleksandr2106/phone_catalog pull request #1
Opened 2019-02-20 17:56 UTC by aleksandr2106

2019-02-21 17:21 UTC, aleksandr2106 commented
Міша, добрий вечір) Слухай,я зробив дз, але в мене ніяк не виходить підключити по адресі наші зображення, можеш мені допомогти з ними,будь ласка?)

2019-02-22 17:11 UTC, zhukmj requested changes
There is no `.prettierrc` and `.editorconfig` files in the project, this cause some code-style issues.

2019-02-22 17:11 UTC, zhukmj commented on src/components/ProductItem/ProductItem.js
> +    var phone_img_link = "http://localhost:3000/";
Don't use `var`. Use `const` or `let` instead.
Also, it's not needed to hardcode `http://localhost:3000/`. Just add a slash `/` at the start of the link

2019-02-22 17:11 UTC, zhukmj commented on src/components/ProductItem/ProductItem.js
> +        <img className="product_item_img" src={phone_img_link} alt={name} />
src={`/${phone_img}`}

2019-02-22 17:11 UTC, zhukmj commented on src/components/ProductListView/ProductListView.js
> +            phone_img={phone.imageUrl}
Don't use underscore in variable/prop names and also don't use "phone", cause theoretically, it can be any product, not only phones (you should make components as universal as possible). Better do `imageUrl={phone.imageUrl}`

2019-02-22 18:54 UTC, zhukmj approved these changes

2019-02-22 18:55 UTC, merged